#!/usr/bin/python3

import sys
from src import data_generator, is_


def usage():
    raise(ValueError(
        'data_generator: generate some .csv files of random data in folder ./data for tests purpose.\
        \n\tneed one and only one argument wich need to be an integer.\
        \n\tex: ./data_generator 10'
    ))


try:
    if (len(sys.argv) != 2):
        usage()
    if (is_.is_int(sys.argv[1]) == False):
        usage()
    count = int(sys.argv[1])
    if (count <= 0):
        usage()
    data_generator.generate_random_data(count)
except ValueError as error:
    print(error)